### ISSUE TITLE
RadListView unbearably slow for few items

### ISSUE THREAD

**Issue by fhackenb** [telerik/nativescript-ui-feedback#1081]
### Tell us about the problem
I have an angular-nativescript POS app that needs to display some inventory items in a grid. I'm using a RadListView to render the list and after upgrading my angular, nativescript, and other library dependencies over the last few months I've noticed the RadListView rendering of the items has gotten unbearably slow. I have multiple "tabs" so you can see different types of items and whenever you switch "tabs" it needs to completely re-render the list with the new times. Before doing some upgrades (which I had hoped would improve app performance) switching tabs would have no significant lag even for rendering 100+ items. Now it takes several seconds to load even 24 (I switched to dynamic rendering on scroll to speed things up but it isn't nearly good enough). 

### Which platform(s) does your issue occur on?
ios (tns ios 5.2.0, 5.3.1) [Angular 7]

### Please provide the following version numbers that your issue occurs with:
- nativescript-ui-listview: 6.1.0
- nativescript-ui-core: 2.0.1
- nativescript-ui-sidedrawer: 6.0.0
- CLI: 5.3.1
- Cross-platform modules: 5.3.1
- Runtime(s): tns-ios 5.3.1

### Please tell us how to recreate the issue in as much detail as possible.
The issue appears to be related to having some nested structures w/in a RadListView. My original code (which ran was unchanged since performing just fine on older versions of {N}, Angular, nativescript-ui:

```
<RadListView id="itemList" top="0" left="0" [items]="displayedInventory" separatorColor="white" [loadOnDemandMode]="loadOnDemandMode"
    (loadMoreDataRequested)="onLoadMoreItemsRequested($event)" class="gridview-wrap-tabs" dock="top" [ngClass]="{'gridview-wrap-tabs': (posLocation && posLocation.tabs)}">
    <ListViewStaggeredLayout tkListViewLayout scrollDirection="Vertical" spanCount="4" itemHeight="180" horizontalAlignment="left"
        class="inventory-list-view-inner" separatorColor="black">
    </ListViewStaggeredLayout>
    <ng-template tkListItemTemplate let-item="item">
        <StackLayout class="inventory-stack-wrap">
            <GridLayout rows="auto, *, auto" columns="auto, auto" orientation="horizontal" class="outerBox" stretchLastChild="true" (tap)="addToCart(item, true)"
                [ngClass]="{ 'portraitBox': orientation==='portrait' , 'selected-inventory-item': item.isSelected, 'empty-inventory-item': item.price < 0}">
                <Label row="0" col="0" *ngIf="item.type==='category'" height="40px" class="price-label-category" [ngClass]="{ 'portrait-category-label': orientation==='portrait' }"
                    text="Category"></Label>
                <Label row="1" col="0" verticalAlignment="top" [text]="item.name" *ngIf="item.type==='category'" class="name-label" textWrap="true"
                    [ngClass]="{ 'portrait-name-label': orientation==='portrait' }"></Label>

                <Label row="0" col="0" verticalAlignment="top" [text]="item.name" *ngIf="item.name && item.name.length <=2 0 && item.type !=='category'"
                    class="name-label" textWrap="true" [ngClass]="{ 'portrait-name-label': orientation==='portrait' }"></Label>
                <Label row="0" col="0" verticalAlignment="top" [text]="item.name.slice(0,20) + '...'" *ngIf="item.name
                    && item.name.length> 20 && item.type !== 'category'" class="name-label" textWrap="true" [ngClass]="{'portrait-name-label': orientation
                    === 'portrait'}"></Label>

                <GridLayout col="0" colSpan="2" row="1" rowSpan="2" width="100%" *ngIf="item.imageSource">
                    <Image class="inventory-image" [ngClass]="{'portrait-inventory-image': orientation==='portrait'}" [src]="item.imageSource"></Image>
                </GridLayout>
                <GridLayout width="100%" *ngIf="item.type !=='category'" row="2" col="0" colSpan="2" columns="auto, *, 10" rows="auto">
                    <Label col="1" row="0" horizontalAlignment="right" height="40px" class="price-label" [ngClass]="{ 'portrait-price-label': orientation==='portrait' }"
                        text="${{item.price | number: '1.2-2'}}"></Label>
                </GridLayout>
            </GridLayout>
        </StackLayout>
    </ng-template>
</RadListView>
```

As a proof of concept to verify that the RadListView rendering is what was slowing it down, I tried it with a just a single label with the item's name embedded in the <ng-template> and the rendering was pretty much instant - so it appears to be a problem with how the RadListView is rendering subitems like StackLayout, GridLayout. I also tried replacing the GridLayout with a DockLayout and removing all the angular *ngIfs and *ngClasses (and removed the Image tag) to see if that would improve performance but it didn't appear to have any effect. Still extremely slow to load just 24 items. (Loading does go up significantly for fewer items - but I can't display fewer than 24 initially)

Any ideas?

**Comment by VladimirAmiorkov** [comment]
Hi @fhackenb ,

First let me describe the current layouts of the `RadListView` and what they are designed for and some of their limitations:
- `ListViewLinearLayout` - this is the most basic layout that renders its elements in vertical or horizontal linear manner. Best performance due to best container reuse and fewer items on the screen at the same time making it the most memory footprint layout.
- `ListViewGridLayout` - similar the `ListViewLinearLayout` but allows the customization to make "multiple" linear layouts using columns. Containers are reused almost as good as the `ListViewLinearLayout` but the memory footprint can get multiple times bigger depending on the columns setup (more items visible at the same time)
- ListViewStaggeredLayout - Worst performance layout due to its design of showing multiple linear layouts in multiple columns with multiple possible different sized elements. This makes full container reuse not possible. This layout should be used to showcase very simple `tkListItemTemplate ` because the is by design the least performance efficient layout.

Looking at your `tkListItemTemplate` I see you have quite a few nested layouts with multiple elements that can change their size at runtime which requires new measure/layout passes combined with `spanCount="4"` is stretching the possibilities of the available CPU/memory.  I also see that you have set the `itemHeight ` of the `ListViewStaggeredLayout ` to a specific value which basically disables the main "staggered" behavior of the layout. I would recommend in this case to better use `ListViewGridLayout` as it is better optimised because it internally set the same size for each item (on iOS).

As next steps I would recommend the following:
- Try to use `ListViewGridLayout` and let us know if the performance has improved and if it is acceptable
- If not, can you provide us with a project that showcases your scenario, you could use our [playground](https://play.nativescript.org/) for faster recreation.

**Comment by fhackenb** [comment]
Thanks for the notes on the different layouts. I had switched it to the ListViewGridLayout and did notice a significant improvement. It is odd though that the performance was fine up until recent {N} / angular updates

**Comment by VladimirAmiorkov** [comment]
Hi @fhackenb ,

I understand, yes we did make quite a few fixes to the layouts to improve/fix some of the issues users were facing with dynamic changes, pull to refresh, load on demand etc. This unfortunately meant that we have to "stop" so of the ways we had limited the layouts so that they are better optimised which is always a hard choice. We are always trying to improve the overall usage of the `RadListView` but due to it having multiple layouts and a low of related functionality it is not an easy balance to have between functionality vs performance.

**Comment by VladimirAmiorkov** [comment]
@fhackenb ,

If you have found a solution to your question you can close this issue.

**Comment by kokosky93** [comment]
I am struggling with poor performance of RadListView too.

@VladimirAmiorkov  could you look at my example and tell is there anything I can improve?

`        <RadListView #upgradesListView [items]="upgrades" [marginTop]="screenWidthDpi * 3" (itemTap)="onUpgradeItemTap($event)" selectionBehavior="None" (itemSwipeProgressEnded)="onSwipeCellFinished($event)" (itemSwipeProgressStarted)="onSwipeCellStarted($event)" (itemSwipeProgressChanged)="onCellSwiping($event)" swipeActions="true">
            <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" spanCount="1"></ListViewGridLayout>
            <ng-template tkListItemTemplate let-item="item">
                <GridLayout class="upgrade-swipe-tile" [ngStyle]="{'height':screenWidthDpi * 32, 'margin-bottom': 1}">
                    <Label verticalAlignment="center" horizontalAlignment="center" [text]="item.Name" [ngStyle]="{'font-size':screenWidthDpi * 9 }" class="upgrade-tile-title"></Label>
                    <StackLayout verticalAlignment="bottom" horizontalAlignment="right" [ngStyle]="{'font-size':screenWidthDpi * 6, 'margin-bottom':screenWidthDpi * 2, 'margin-right':screenWidthDpi * 4}" orientation="horizontal">
                        <Label [text]="item.Mileage +' km'" class="upgrade-tile-extra-info"></Label>
                        <Label [text]="item.Date | date:'yyy/MM/dd'" class="upgrade-tile-extra-info" [ngStyle]="{'margin-left':screenWidthDpi * 4 }"></Label>
                    </StackLayout>
                    <Label verticalAlignment="bottom" horizontalAlignment="left" text="&#xf7d9;" [ngStyle]="{'font-size':screenWidthDpi * 18, 'margin-bottom':screenWidthDpi * 2,'margin-left':screenWidthDpi * 2 }" class="fas upgrade-icon"></Label>
                    <label class="shadow-down" [ngStyle]="{'height':screenWidthDpi }" verticalAlignment="bottom"></label>
                </GridLayout>
            </ng-template>

            
            <GridLayout *tkListItemSwipeTemplate columns="auto, *, auto">
                <GridLayout (tap)="updateUpgradeSwipe($event)" class="swipe-edit-button" visibility="collapsed" id="left-stack" columns="*" col="0">
                    <Label id="mark-view" text="&#xf044;" [ngStyle]="{'font-size':screenWidthDpi * 14 }" class="fa swipe-edit-button-icon" verticalAlignment="center" horizontalAlignment="center"></Label>
                    <label class="shadow-down" [ngStyle]="{'height':screenWidthDpi }" verticalAlignment="bottom"></label>
                </GridLayout>
                <GridLayout (tap)="removeUpgradeSwipe($event)" class="swipe-remove-button" visibility="collapsed" id="right-stack" [ngStyle]="{'padding-top':screenWidthDpi * 0.1, 'padding-bottom':screenWidthDpi * 0.1 }" columns="*" col="2">
                    <Label id="delete-view" text="&#xf1f8;" [ngStyle]="{'font-size':screenWidthDpi * 14 }" class="fa swipe-edit-button-icon" verticalAlignment="center" horizontalAlignment="center"></Label>
                    <label row="0" class="shadow-down" [ngStyle]="{'height':screenWidthDpi }" verticalAlignment="bottom"></label>
                </GridLayout>
            </GridLayout>
        </RadListView>`
