### ISSUE TITLE
showOverNavigation is not working 

### ISSUE THREAD

**Issue by gauravbabu74** [telerik/nativescript-ui-feedback#130]
Please give me an example for showOverNavigation. I am working on nativescript with angular project. If this issue is persist already please resolved as soon as possible. And give me update at gauravbabu74@gmail.com or reply on this.

Thanks

**Comment by VladimirAmiorkov** [comment]
Hi @gauravbabu74 ,

Please refer to my response regarding this feature in this issue https://github.com/telerik/nativescript-ui-feedback/issues/61#issuecomment-286466919

**Comment by gauravbabu74** [comment]
Thanks for the update @VladimirAmiorkov

**Comment by shiamalon** [comment]
I got a similar effect  (don't know if good or not, just started nativescript a couple months ago)

The idea is on detecting drawer changing:
1- change the visibility of the action bar
2 - show the stacklayout item that replaces the action bar (this helps so that your page don't slide up when you collapse the actionbar)

 **component**

`import { ActionBar} from "ui/action-bar";`
`import {Page} from "ui/page";`
`...`
` constructor(...,private page:Page)`
`...`
`//variable to control the stacklayout that will replace the action bar`
`  isItemVisible:boolean = false;`
`//control what happens to the action bar when drawer is opening`
` drawerOpening(){`
`         let actionbar:ActionBar = <ActionBar>this.page.getViewById("propertyActionBar");`
`        console.log("atopen"+actionbar.visibility);`
`            this.isItemVisible=true;`
`           actionbar.visibility='collapsed';`
`    }`


 `   onDrawerClosing(){`
 `       let actionbar:ActionBar = <ActionBar>this.page.getViewById("propertyActionBar");`
 `        this.isItemVisible=false;`
`         actionbar.visibility='visible';`
`    }`

**html**
`
<ActionBar id="propertyActionBar"...
....
<RadSideDrawer #drawerComponent tkToggleNavButton transition="SlideInOnTopTransition" (drawerOpening)="drawerOpening()" (drawerClosing)="onDrawerClosing()">
...
 <StackLayout tkMainContent>
        <StackLayout class="action-bar" style="height:60;" [visibility]="isItemVisible ? 'visible' : 'collapsed'">
        </StackLayout>....`

Although a bit clumsy it's enough for the current project phase. Is there a better way to do this though?
  @VladimirAmiorkov is there any ETA for this feature?

**Comment by shiamalon** [comment]
Thanks @VladimirAmiorkov !

**Comment by JPM84** [comment]
Hi, I tried the RC-Tag with "nativescript-ui-samples-angular" project but the showOverNavigation feature is not working in Android. Am I doing something wrong or is this not yet included in the RC?

**Comment by VladimirAmiorkov** [comment]
@JPM84 Are you deploying it to lower than API 21 by any chance, we had that issue which will be resolved in our upcoming 2.0.0 release.

**Comment by JPM84** [comment]
@VladimirAmiorkov Thx! I switch to a newer device and it's working fine 👍. My older test device (Nexus 5 – API 23) was the problem. It's showing the sidedrawer under the actionbar.

**Comment by VladimirAmiorkov** [comment]
@JPM84 Hmm if it was with API 23 there should have not been such issues, maybe you where using a lower version of the nativescript-telerik-ui plugin ?

**Comment by VladimirAmiorkov** [comment]
Hi all,

This is a duplicated issue so please continue any discussions [here](https://github.com/telerik/nativescript-ui-feedback/issues/61).
