### ISSUE TITLE
Dynamic CSS not applied (iOS only)

### ISSUE THREAD

**Issue by ignaciofuentes** [telerik/nativescript-ui-feedback#135]
https://www.screencast.com/t/tliIofXIF

Steps:

- tns create my-project-name --template nativescript-template-drawer-ts
- cd my-project-name
- tns run ios

**Comment by VladimirAmiorkov** [comment]
Hi @ignaciofuentes ,

Currently we are in the process of migrating the nativescript-telerik-ui/-pro plugin to the next major update to NativeScript 3.0 and I tested this in our internal in development version of the plugin. I can confirm that this issue is not reproducible in that internal version.

We have planned to release a RC of nativescript-telerik-ui that will be compatible with 3.0 by the end of March and you should be able to test this on your end.

**Comment by ginev** [comment]
This issue will be resolved in the upcoming NS UI release.
