### ISSUE TITLE
RadListView does not accept padding styling

### ISSUE THREAD

**Issue by dgomezs** [telerik/nativescript-ui-feedback#152]
hi there, 

I'm trying to add some padding at the bottom of my RadListView but it seems this is not possible either by using paddingBottom or style="padding-bottom". The reason i'm trying to use the padding is because I have a [floating button]( https://github.com/bradmartin/nativescript-floatingactionbutton) and I want to add some space at the bottom so that when scrolling i can go to the bottom and see the last element of the list on top of the floating bottom. 

Any ideas how to get it done if not with the padding?
Thank you in advanced.

**Comment by ginev** [comment]
@dgomezs, padding is not supported on list controls. You may try to insert a custom business object in your source used to feed the list that does not contain any values on its properties. This will hide any texts on the item template and will produce an empty list item which will work as a "padding" item.

**Comment by dgomezs** [comment]
@ginev thank you for the information. I'll try that approach

**Comment by ginev** [comment]
@dgomezs, you can actully do that with the List Footer feature: http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/header-footer

**Comment by dgomezs** [comment]
@ginev I know this but the header and footer are not working properly know on IOS. There are couple of issues blocking me from using them on my IOS app 

https://github.com/telerik/nativescript-ui-feedback/issues/158
https://github.com/telerik/nativescript-ui-feedback/issues/94

Once they are solved I will just use the footer

**Comment by ginev** [comment]
@dgomezs, okay - we have addressed the Grid Layout issue (#94) with header/footer not being sized correctly in our internal codebase. We will escalate the other as well.

**Comment by dgomezs** [comment]
@ginev great. Looking forward to the next version

**Comment by ginev** [comment]
@dgomezs, #158 is acutally related to the behavior of NS in context with the List on iOS. When dynamically making elements within list items hidden/visible you might experiences glitches. This is what happens here. You are making the footer initially hidden which makes it impossible to show afterwards on iOS according to the ngIf condition. This comes from the way UICollectionView (the iOS list component) works. Instead of doing this, you may want to try "hiding" the footer by simply making its text transparent or something like that.
