### ISSUE TITLE
iOS picker value alignment

### ISSUE THREAD

**Issue by vcooley** [telerik/nativescript-ui-feedback#165]
iOS picker values are misaligned when compared to other values in a data form.
![image](https://cloud.githubusercontent.com/assets/12551141/25594004/9bf0370a-2e84-11e7-911a-ef7b896f1d8c.png)

I was able to fix this with the following code:
```
<TKPropertyEditor tkEntityPropertyEditor type="Picker">
    <TKPropertyEditorStyle tkPropertyEditorStyle ios:editorHorizontalOffset="4">
    </TKPropertyEditorStyle>
</TKPropertyEditor>
```

**Comment by tgpetrov** [comment]
Thanks for pointing this out. We will go through all editors and ensure that they are all aligned with each other. We are having a release later this week, so this fix will be included later.

**Comment by Natalia-Hristova** [comment]
Hi @vcooley ,

This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` . 

**NOTE** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.
