### ISSUE TITLE
[RadListView] Why doesn't scrollToIndex method utilize animation?

### ISSUE THREAD

**Issue by NordlingArt** [telerik/nativescript-ui-feedback#167]
In iOS, I know it's only a variable that's been set to false in the source code:

```js
this._ios.scrollToItemAtIndexPathAtScrollPositionAnimated(
  NSIndexPath.indexPathForItemInSection(index, 0),
  1 /* Top */,
  false // <-- should be true if animated
);
```

Shouldn't such a simple boolean value be available to the public method `scrollToIndex`? Example:

```js
const animateScroll = true;
radListView.scrollToIndex(2, animateScroll);
```

**Comment by VladimirAmiorkov** [comment]
Hi @NordlingArt ,

Thank you for the suggestion. Indeed exposing such functionality will be useful in the nativescript-telerik-ui plugin. Currently it is not exposed because such functionality is not available in the underneath Android library of the RadListView and since providing features only for one platform is not a good experience this functionality has not been provided to iOS event tho it looks as a simple feature.

We have increased the priority of this feature for both iOS and Android and will do our best to implement it as soon as possible.
