### ISSUE TITLE
[RadListView] {N} ListView and RadListView have misaligned properties in EventData.

### ISSUE THREAD

**Issue by MIYankov** [telerik/nativescript-ui-feedback#189]
Trying to migrate from a {N} ListView to RadListView can be a pain due to misalignment in the EventData of the two controls while they represent the same event.

{N} ListView EventData -
 http://docs.nativescript.org/apireference/interfaces/_ui_list_view_.itemeventdata.html

RadListView EventData - http://docs.telerik.com/devtools/nativescript-ui/api/classes/listvieweventdata.html

The thing I encountered was that the 'itemIndex' property is called 'index' in RadListView and the {N} ListView exposes the a 'view' property while I had to call 'eventData.object' in RadListView.

I think it will be best in general if properties are aligned with interfaces in {N}.

**Comment by ginev** [comment]
@MIYankov, this issue will be resolved in NS UI 3.0. Note that there will be a breaking change:
- the `object` property will no longer return the Swipe Content View when using the `args` object of the `itemSwipe...` events. The Swipe Content View will be accessible through the `swipeView` property.

**Comment by Natalia-Hristova** [comment]
Also, the fix is available in the "next" version of the nativescript-telerik-ui-pro plugin where you can test it out. Simply install that version of the plugin: tns plugin add nativescript-telerik-ui-pro@next . 
**Note** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.
