### ISSUE TITLE
Bug Issue while updating the ListView content while using ListViewStaggeredLayout

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#214]
The issue appears when you try to update the ListView content from code behind. The ListView is not refreshed properly and the items are not shown. This happens only on Android while using ListView with `ListViewStaggeredLayout`
I am attaching a sample project, which could be used for debugging.
[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/1083977/Archive.zip)

**Comment by ginev** [comment]
This seems to be a problem with the Android SDK and the StaggeredLayout implementation in particular:
https://stackoverflow.com/questions/26860875/recyclerview-staggeredgridlayoutmanager-refresh-bug

A workaround: instead of creating the ObservableArray each time, simply splice it: `array.splice(0, array.length);`
