### ISSUE TITLE
3.0: Why SlideAlongTransition got dropped for showOverNavigation="true" situations?

### ISSUE THREAD

**Issue by sserdyuk** [telerik/nativescript-ui-feedback#225]
Was my favorite setup on iOS in version 2. Seemed to work just fine. Why?

**Comment by sserdyuk** [comment]
```
<drawer:RadSideDrawer.drawerTransition>
      <ios>
        <drawer:SlideAlongTransition/>
      </ios>
    </drawer:RadSideDrawer.drawerTransition>
```
produces the following error at runtime after upgrading to v3:

`CONSOLE LOG file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer-common.js:129:28: Warning: 'SlideAlongTransition' is not supported when 'showOverNavigation' is set to 'true'.`

**Comment by ginev** [comment]
Hello @sserdyuk ,

There was a breaking change with RadSideDrawer which was recently introduced and is described here:

http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/show-over-navi-bar

Among these changes is an incompatibility introduced with the `showOverNavigation` and `SlideAlongTransition`

Can you confirm that the instructions on this page are helpful?

**Comment by VladimirAmiorkov** [comment]
Hi @sserdyuk ,

I would like to give you some additional information on why some transitions have been removed from the supported list when the RadSideDrawer is used with `showOverNavigation="true"`.

When initially implementing this "over action bar" functionality, the {N} + Angular functionality was still in its initial development efforts and was not considered as a general direction for this feature of the RadSideDrawer. Due to many internal differences when it comes to parsing Vanila {N} XML and Angular's HTML to native iOS/Android elements from which some are out of the scope control of the RadSideDrawer (like the ActionBar) the initial implementation that used the `DrawerPage` was incompatible between Vanila {N} and Angular + {N}. This was discussed in the team internally extensively and due to the popularity of Angular compatibility increasing a decision was made to reimplement this feature and make it more streamline so that it could be shared between Vanila {N} and Angular + {N}, unfortunately some breaking changes were necessary.

I want to ensure you that we will be reviewing this feature and the removal of those transitions to see if we can bring them back into the supported transitions list in the next official release. We want to apologize for any inconvenience that this may be causing.

**Comment by sserdyuk** [comment]
@VladimirAmiorkov I think you need to document these things in the "breaking changes" section. Also, I am a "vanilla" NS user, and it's concerning to see that it's somewhat a second priority to the company. Thank you for the follow up.

**Comment by VladimirAmiorkov** [comment]
Hi @sserdyuk ,

This breaking change was introduced with our 2.0.0 release and was documented [here](http://docs.telerik.com/devtools/nativescript-ui/release-notes#release-notes-200) in our release notes for that version. Additionally there is an article describing the process of migrating the "show over navigation bar" feature in Vanila {N} between 1.x.x to 2.x.x that can be found [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/show-over-navi-bar#migrating-from-drawerpage-versions-1xx-to-the-latest-version).

I want to ensure you that the Vanila {N} is not considered second priority but rather Angular + {N} is now also considered on the same part as Vanila {N} is. What I wanted to say with my previous comment was that previously Angular + {N} was not considered due to it was still in very much early development on both Google's and ours part and now both approaches for developing {N} apps are considered with the same priority. Actually technically Angular + {N} cannot exist without Angular + {N} so we are focusing on both with the same priority but as described now we have two factors with its own technical challenges that we are considering and have to take into account.

**Comment by sserdyuk** [comment]
@VladimirAmiorkov I politely disagree. The change we are discussing here is a feature silently removed on transition from v2 -> v3. The document you and @ginev linked here speaks about changes in v1 -> v2. The transition already worked in v2 with the new `showOverNavigation` design.

**Comment by VladimirAmiorkov** [comment]
@sserdyuk You are correct those animations was available in the 2.x.x version. In that version they were animating with incorrect and sometimes impossible animations causing errors, confusion or very poor performance. This was not what we wanted to have under as supported transitions which is what they were actually removed in 3.x.x when used with the showOverNavigation enabled.

I have reverted this change in our _next_ version of the plugin in order to make this change immediately available for you so that you will be able to test it with our latest 3.x.x improvements. Can you test this functionality of the transition and let us know what you think of its performance and overall usage of the `SlideAlongTransition` when used with `showOverNavigation` in both iOS and Android. Currently we are aware of an issue with that transition on Android which are caused by a limitations from the NativeScript core framework itself that does not allow us to overcome in both Vanila {N} and Angular + {N}. This was the main reason why some transitions was removed in the first place.

To test our next version simply do:

- `tns plguin add nativescript-telerik-ui@next` or `tns plguin add nativescript-telerik-ui-pro@next`

or 

- change your package.sjon to: `"nativescript-telerik-ui": "next" ` or `"nativescript-telerik-ui-pro": "next" `

**Comment by sserdyuk** [comment]
@VladimirAmiorkov I have tested it on iOS, and everything is looking good. I have not been using it on Android, as another transition blends better in Android experience, but I have switched to SlideAlong just to try, and it definitely has problems on all my devices and API levels. Specifically, improper overlapping at the beginning of the transition. Is there a way you could keep the transition on iOS only?

**Comment by VladimirAmiorkov** [comment]
@sserdyuk Yes that is the currently limitation that I was talking about for Android.

As we try to be consistent across both platforms at the same time, we try to not release APIs that would lead to inconsistent behavior, which was the reason for the removal of those transitions in both iOS and Android.

Due to seeing that even with such inconsistency those transitions are beneficial to the users of RadSideDrawer, we will be reverting to allowing them again even with `showOverNavigation` causing the mentioned issues. Yes you will be able to use you current setup of `SlideAlongTransition` for iOS and a different transition for Android with our next official release just as you are with our "next" version. The "next" version is a special tagged version that we upload to npmjs.com that is taken from our hourly/daily updated branch of the plugin and it includes all of the new features and bug fixes that will be available in the next official version. You can use that version without any problems but be aware because of the nature of that version and it being updated hourly/daily it should not be considered for production, we do try to keep it stable.

**Comment by sserdyuk** [comment]
@VladimirAmiorkov Thank you. I'll just set it to today's next as `"nativescript-telerik-ui": "3.1.0-2017-7-4-2",` until 3.1.1 is released.

**Comment by tsonevn** [comment]
SlideAlongTransition seems to work as expected while showOverNavigation is set up to true with UI for NAtiveScript 3.2
