### ISSUE TITLE
SideDrawerModule with webpack angular

### ISSUE THREAD

**Issue by behi1ty** [telerik/nativescript-ui-feedback#234]
import { NativeScriptUISideDrawerModule, SIDEDRAWER_DIRECTIVES } from "nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives";

    imports: [
        .......
        NativeScriptUISideDrawerModule,
    ],
    declarations: [
        ...,,
        SIDEDRAWER_DIRECTIVES,
       .....
]

nativescript     │ 3.1.2        
tns-core-modules │ 3.1.0  
tns-android      │ 3.1.1   
webpack | 0.7.1

ERROR in Type RadSideDrawerComponent in D:/Mobile/TimeWin/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts is part of the declarat
ions of 2 modules: NativeScriptUISideDrawerModule in D:/Mobile/TimeWin/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts and AppMod
ule in D:/Mobile/TimeWin/app/app.module.ts! Please consider moving RadSideDrawerComponent in D:/Mobile/TimeWin/node_modules/nativescript-telerik-ui/sidedrawer/angula
r/side-drawer-directives.d.ts to a higher module that imports NativeScriptUISideDrawerModule in D:/Mobile/TimeWin/node_modules/nativescript-telerik-ui/sidedrawer/ang
ular/side-drawer-directives.d.ts and AppModule in D:/Mobile/TimeWin/app/app.module.ts. You can also create a new NgModule that exports and includes RadSideDrawerComp
onent in D:/Mobile/TimeWin/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts then import that NgModule in NativeScriptUISideDrawerM
odule in D:/Mobile/TimeWin/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts and AppModule in D:/Mobile/TimeWin/app/app.module.ts.

**Comment by VladimirAmiorkov** [comment]
Hi @behi1ty ,

When using the RadSideDrawer in and Angular + {N} app you need only `NativeScriptUISideDrawerModule` or `SIDEDRAWER_DIRECTIVES` imports, not both at the same time as the module already imports the directives. When you want to build you app with AoT enabled you need to use the `NativeScriptUISideDrawerModule` and shown in the documentation [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started#using-the-ngmodule-of-the-plugins-ui-components)

All that you need to resolve this issue is remove the import for the `SIDEDRAWER_DIRECTIVES`, those are leftover from the pre AoT implementation.
