### ISSUE TITLE
RadAutoCompleteTextView close button event?

### ISSUE THREAD

**Issue by nmongiya** [telerik/nativescript-ui-feedback#315]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
Yes

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
nativescript 3.2.0
nativescript-pro-ui ^3.1.2

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_

**Comment by tgpetrov** [comment]
Hi @nmongiya,

Currently there is no such event.
Thank you for the suggestion, we will consider it for some of our next versions.

**Comment by tgpetrov** [comment]
Hi @nmongiya with `nativescript-ui-autocomplete` [3.6.0](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/autocomplete.md#v360) there is a `textChanged` event which you can use to get notified when the text is changed including when the X button is pressed.

**Comment by pnahtanoj** [comment]
The textChanged event is not comparable - an empty string is not the same thing as a user action to dismiss.

**Comment by pnahtanoj** [comment]
Maybe I misread - which property of the textChanged event would tell you X was pressed?

**Comment by tgpetrov** [comment]
@pnahtanoj Currently, there is no property in textChanged that tells you if the change was caused by pressing 'X' or backspace, but it sounds like a good idea. 

Can you elaborate more about the use case? The 'X' button's function is to clear the whole text. If I am a user and type "A"s in RadAutoComplete, then I change my mind and decide I wanted to type "B", I can either press backspace or press the 'X' button to remove the "A" and both would lead to the textChanged event and the information that the text is now empty. 

From the user's perspective it seems like the same thing, why would you need differentiate between the two?

**Comment by hrebeniuk** [comment]
How i can emit close button event?
Example: on change title i clean current country on RadAutoCompleteTextView
