### ISSUE TITLE
Pre-selected Token for RadAutoCompleteTextView (Angular 2)

### ISSUE THREAD

**Issue by Sharique-Hasan** [telerik/nativescript-ui-feedback#323]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
_Yes/No_
YES

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._
I am unable to show the pre-selected token.

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`) next
- **CLI:** (run `tns --version` to fetch it) 3.2.1
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`) 3.2.0
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`) 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_

How Do I tell RadAutoCompleteTextView about my pre-selected token to show. Every time it start showing empty field. How can I set the token from my component? (Angular 2)

**Comment by VladimirAmiorkov** [comment]
Hi @Sharique-Hasan ,

Thank you for contacting us. In order to achieve the described behavior you can take advantage of the [addToken](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radautocompletetextview.html#addtoken) method which will add any valid [TokenModel](http://docs.telerik.com/devtools/nativescript-ui/api/classes/tokenmodel.html) object to the [RadAutoCompleteTextView](url).

I created a simple example that shows the described approach, you can find it in the master branch of the sdkAngular repository [here](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/sdkAngular/app/autocomplete/preselected-tokens).

I will close this issue, if you have any other questions please let us know.

**Comment by tiwari-rahul** [comment]
Tried with example mentioned.
Pre-selected tokens are not showing .
Add Next Token button also not working.

**Comment by behrangs** [comment]
@VladimirAmiorkov  I can confirm that the addToken method doesn't work the way explained by the example(). However, I managed to get it to work this way:

`
    public onLoaded(args) {
        let auto: RadAutoCompleteTextView = <RadAutoCompleteTextView>args.object;Ï
        auto.addToken(INSERT_TOKEN_AS_EXPLAINED_BY_EXAMPLE);
    }`

You'll obviously need to add `(loaded)="onLoaded($event)"` in your html tag as well.

**Comment by n0mer** [comment]
@VladimirAmiorkov correct link for example is https://github.com/NativeScript/nativescript-ui-samples/tree/master/autocomplete/app/examples/preselected-tokens , instead of https://github.com/telerik/nativescript-ui-samples-angular/tree/master/sdkAngular/app/autocomplete/preselected-tokens
