### ISSUE TITLE
RadListView swipe action doesn't work when it is in a TabView

### ISSUE THREAD

**Issue by erkanarslan** [telerik/nativescript-ui-feedback#337]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
Yes

### Tell us about the problem
I hava a page that contains a TabView with 2 tabs. In the second tab I have a RadListView. I am trying to implement swipe actions on items in that. It doesn't work. List view items swipe around 10 dp and then goes back to its original place. I cannot get a full swipe.

I tested my code without TabView. It works well. But when I put RadListView into a TabView, swipe doesn't work as expected. Probably TabView blocks swipe action on the RadListView as it also uses swipe gesture to change the tabs.

### Which platform(s) does your issue occur on?
Android. Not tested on iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.1.3
- **CLI:** 3.2.1
- **Cross-platform modules:** 3.2.0
- **Runtime(s):** 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Get a copy of nativescript-ui-samples-angular
2. Run it, swipe actions work
3. Put the RadListView into a TabView in the same page
4. Run it, swipe actions don't work

**Comment by NickIliev** [comment]
@erkanarslan this is expected behavior related to Android touch event thief (good blog post [here](https://mobiarch.wordpress.com/2013/11/21/prevent-touch-event-theft-in-android/)). Ther are some possible hacky solutions that will require for you to change the source code of tab-view which is not recommended. However, if you are interested in these solutions, you can look at [this thread](https://github.com/NativeScript/NativeScript/issues/958#issuecomment-233332186)
