### ISSUE TITLE
RadListView with Nativescript+Vue.js

### ISSUE THREAD

**Issue by vvarda** [telerik/nativescript-ui-feedback#341]
How to implement RadListView in Vue project correctly?

In main.js:
`import { RadListView } from 'nativescript-pro-ui/listview'`
`Vue.registerElement('rad-list-view', () => RadListView);`

In component:
```
<rad-list-view :items="categories">
     <template scope="item">
        <stack-layout>
            <label :text="item.title"></label>
            <label :text="item.description"></label>
        </stack-layout>
    </template>
</rad-list-view>
```

```
export default {
    data () {
      return {
        categories: [
          {
            title: 'Test 1',
            description: 'Test 1 description'
          },
          {
            title: 'Test 2',
            description: 'Test 2 description'
          },
          {
            title: 'Test 3',
            description: 'Test 3 description'
          }
        ]
      }
    }
  }
```
![1508174136516](https://user-images.githubusercontent.com/4321362/31625466-d9bd7fee-b2ae-11e7-9b7e-cec4d243b896.jpg)

But it doesn't work well. It only displays [object Object] rows.
![1508174334921](https://user-images.githubusercontent.com/4321362/31625600-4034f8f6-b2af-11e7-87b0-6f5414efeafc.jpg)

Any ideas?

**Comment by VladimirAmiorkov** [comment]
Hi @vvarda ,

It looks to me that the declared:

```
<template scope="item">
        <stack-layout>
            <label :text="item.title"></label>
            <label :text="item.description"></label>
        </stack-layout>
 </template>
```

is not being utilized and registered by the RadListView at all. By design the `RadListView` in NativeScript has its own property [itemTemplate](http://docs.telerik.com/devtools/nativescript-ui/api/classes/radlistview.html#itemtemplate) that is used as "template", an example can be found [here](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/listview/getting-started/getting-started.xml#L4-L9). I am not yet that much familiar with VueJS as it is still not fully supported in NativeScript so if you are aware of any technique that can be used to "map" an VueJS template `(<template></template>`) to that {N} property of the RadListView that should would work. For example in {N} + Angular we are taking advantage of Angular's **custom inline directives** (_tkListItemTemplate_) approach to set the properties of the RadListView from the Angular HTML declaration, as shown [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/listview/getting-started/listview-getting-started.component.html#L4-L9))

**Comment by vvarda** [comment]
@VladimirAmiorkov plz check [Vue slots article](https://vuejs.org/v2/guide/components.html#Scoped-Slots) and [short ListView working example](https://github.com/tralves/nativescript-vue-template/blob/master/app-with-list-view.js).

Maybe, then you could help me.

**Comment by prince30** [comment]
Can someone help me with the above issue

**Comment by RosilBelli** [comment]
Is there any light on this? I'm also trying to use the RadListView without success. Only [object,object] is listed, unless it is an array of strings. Thanks!

**Comment by Quadrophone** [comment]
I got this working:

in main.js:

`Vue.registerElement('RadListView', () => require('nativescript-ui-listview').RadListView)`

in the component:

```
<RadListView :items="photos" ref="photos">                            
</RadListView>
```

And then in the mounted() event:

```
let template = `<Image src="{{path}}" />`
this.$refs.photos.nativeView.itemTemplate = template;
```

Assuming you have an array of photo objects, each with a `path` property

**Comment by odai-alali** [comment]
take a look at this https://play.nativescript.org/?template=play-vue&id=i28vZu&v=4
This was mentioned in Igor's [answer](https://github.com/nativescript-vue/nativescript-vue/issues/245#issuecomment-396525608)

**Comment by msaelices** [comment]
The 3.7.0 version is supporting Vue :)

See https://github.com/msaelices/ns-ui-vue-demo/
