### ISSUE TITLE
RadListView w/ ListViewStaggeredLayout not displaying images from remote URL (NG2)

### ISSUE THREAD

**Issue by kinggolf** [telerik/nativescript-ui-feedback#35]
Using nativescript, tns-core-modules, tns-android, & tns-ios all on version 2.4.0, nativescript-telerik-ui version 1.5.1, and angular 2.2.1. I am trying to load images from a remote server into my app using RadListView w/ ListViewStaggeredLayout and html like "<Image [src]='remote url'...
When I try this with ListViewLinearLayout the remote images load fine, but with ListViewStaggeredLayout (2 cols) the images do not display.

I created a [github repo](https://github.com/kinggolf/staggered) that shows this behavior and I included an option to load local images with a random time delay. Even in this case the images load nicely over time w/ ListViewStaggeredLayout. Also, I posted this same [question on stackoverflow](http://stackoverflow.com/questions/40697620/nativescript-angular2-telerik-ui-radlistview-issue-displaying-images-from-remote/40706694#40706694).

Maybe there is a better method of managing and displaying photos from a remote server but if ListViewLinearLayout w/ images from remote server loads nicely and ListViewStaggeredLayout w/ time delayed local images loads nicely, then why not ListViewStaggeredLayout from remote server? Also, why can I not use "loadMode='async'" with ListViewStaggeredLayout? Thanks.

**Comment by VladimirAmiorkov** [comment]
Hi @kinggolf ,

Thank you for reporting this issue to us. I noticed that in the mentioned repository there are only resources for iOS, does that mean you are experiencing those issues only on that platform? Unfortunately the use of the `loadMode='async'` of the `Image` in {N} is not supported for the `ListViewStaggeredLayout` because of the native of that specific native layout. Let me give you some more details of what that layout is and how it is implemented in the iOS framework, in order for that layout to manage the "dynamic and different" size of each ListView's cell it "requires" the size of that cell to be determined during initialization of that cell and its content. This means that for example if an image is to be placed in such cell that image needs to have its final size ready so that the native iOS framework can layout it accordingly. This is the short description of why when the loadMode is set to async the cells in the RadListView's ListViewStaggeredLayout are not rendered accordingly. In Android loading and managing images can be done via our [nativescript-fresco](https://www.npmjs.com/package/nativescript-fresco) plugin which uses the native Android Fresco library for loading remote resource images into an Android application.

Hope this information is helpful, in iOS when using `ListViewStaggeredLayout` you need to make sure that the size of the cell can be determined at initialization in order for its built-in "staggered" layout mechanism to work as expected.

**Comment by kinggolf** [comment]
@VladimirAmiorkov Thanks for the response and explanation, this helps a lot. I have not tested yet on Android.

**Comment by kinggolf** [comment]
@VladimirAmiorkov Now I have added new pages to my app. When the app navigates from a page with either ListViewStaggeredLayout or ListViewLinearLayout to a new page and then returns back to original page using iOS back button, the app does not display the original view, and in fact the app freezes w/ no error messages. I have updated this [github repo](https://github.com/kinggolf/staggered) to show this.
Sorry for pinging you on this, but you have been the only one to help me so far with ListViewStaggerLayout, which I really appreciate.

**Comment by VladimirAmiorkov** [comment]
@kinggolf 

I took a look at the provided github repo application and was able to observe the described issue. It is caused by an incompatibility between the nativescript-agnular (1.1.3) and angular (2.2.1) dependencies. The 2.2.1 version requires the latest 1.2.0 version of nativescript-agnular.

Simple updated your package.json to:

```
"dependencies": {
  "@angular/common": "2.2.1",
  "@angular/compiler": "2.2.1",
  "@angular/core": "2.2.1",
  "@angular/forms": "2.2.1",
  "@angular/http": "2.2.1",
  "@angular/platform-browser": "2.2.1",
  "@angular/platform-browser-dynamic": "2.2.1",
  "@angular/router": "3.2.1",
  "nativescript-angular": "1.2.0",
  "nativescript-iqkeyboardmanager": "1.0.1",
  "nativescript-ng2-fonticon": "1.3.3",
  "nativescript-theme-core": "0.2.3",
  "nativescript-telerik-ui": "1.5.1",
  "reflect-metadata": "~0.1.8",
  "rxjs": "5.0.0-beta.12",
  "tns-core-modules": "2.4.2"
},
```
