### ISSUE TITLE
Android vs iOS RLV sizing

### ISSUE THREAD

**Issue by NathanaelA** [telerik/nativescript-ui-feedback#37]
This is a iOS only issue; Android has no issues.   Using TNS 2.4.0 and TUI 1.5.1

In android if I create a Template inside a RLV

```
<lv:RadListView row="0" rowSpan="2" colSpan="2" id="lines" itemTap="cardClick" itemLoading="gridItemLoading">
            <lv:RadListView.listViewLayout>
                <lv:ListViewGridLayout scrollDirection="Vertical" spanCount="1"/>
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
<StackLayout>  ... template stuff ...  </StackLayout>        
            </lv:RadListView.itemTemplate>
</lv:RadListView>
```

On Android it actually figures out the sizes and display everything correctly.   On iOS, it appears to figure out the sizes; but then displays the cells like they are 50dp sized cells.

![image](https://cloud.githubusercontent.com/assets/850871/20610672/59f2a84a-b262-11e6-9b6a-1277166b8401.png)

If you scroll PAST the bottom you will see this:

![image](https://cloud.githubusercontent.com/assets/850871/20610709/e3f853e6-b262-11e6-946d-290263d8c7b0.png)

If you popup the notification center (by dragging down from the top of the screen) and this dismiss it; you see this:
![image](https://cloud.githubusercontent.com/assets/850871/20610721/27ecc53c-b263-11e6-8e5c-dc9aad19db92.png)

As you can see the data inside the CELLS are rendered properly; but the cells themselves are NOT calculating the size they need to be on iOS.

**Comment by NickIliev** [comment]
@NathanaelA  this issue was handled by introducing `itemHeight` for the items templates. Although Android can handle the sizes without explicitly setting the height of the cells, on iOS the itemHeight must be set (or at least the parent layout element of the cell should have predefined item height).

Property described in[ this documentation article](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/item-layouts#defining-a-specific-item-layout)
