### ISSUE TITLE
DataForm Boolean field not works properly #324

### ISSUE THREAD

**Issue by manigorsh** [telerik/nativescript-ui-feedback#372]
https://github.com/telerik/nativescript-ui-feedback/issues/324
I updated to "nativescript-pro-ui": "^3.1.4" and this bug still presents. So why did you closed that issue?

**Comment by NickIliev** [comment]
@manigorsh, as discussed in the linked issue the fix, will be included in version 3.2.0. Meanwhile, if you want to test the fix with your project, you can install the **next** version instead of the official "nativescript-pro-ui": "next"

```
tns plugin remove nativescript-pro-ui
tns plugin add nativescript-pro-ui@next
rm -rf platforms
tns run android
```

Keep in mind that this is beta version meant only for testing purposes and should not be used in production. Please let me know if the provided version is resolving your case.

**Comment by NickIliev** [comment]
@manigorsh FYI: nativescript-pro-ui 3.2.0 is now live - let us know if the latest version is resolving your issue.

**Comment by manigorsh** [comment]
@NickIliev, yes it works properly now. Thanks!
