### ISSUE TITLE
RadLegendView stopped working after updating nativescript-pro-ui to 3.2.0

### ISSUE THREAD

**Issue by bnbs** [telerik/nativescript-ui-feedback#382]
```
<RadPieChart allowAnimation="true">
    <DonutSeries tkPieSeries selectionMode="DataPoint" outerRadiusFactor="0.9" expandRadius="0.4" outerRadiusFactor="0.7" innerRadiusFactor="0.4"
        [items]="dados" valueProperty="Value" legendLabel="Category" showLabels="true"></DonutSeries>

    <RadLegendView tkPieLegend position="Bottom" [title]="chartTitle" offsetOrigin="TopRight" width="140" enableSelection="true"></RadLegendView>
</RadPieChart>
```
After updating nativescript-pro-ui to 3.2.0 the RadLegendView stopped showing.

**Comment by NickIliev** [comment]
@brunaaanayara 

We have the exact same example demonstrated [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/chart/series/pie/chart-series-pie.component.html#L10-L15) and it works as expected on my side. (I have also changed to `Bottom`position and using binded `title` but again everything seems to work as expected).

Let me know if there are any additional code or steps involved and or even better provide full demo project that can reproduce the issuel.

**Comment by brunaaanayara** [comment]
[here](https://github.com/telerik/nativescript-ui-feedback/files/1440853/chartTest.zip) is a demo that reproduce the issue.

**Comment by NickIliev** [comment]
@brunaaanayara thank you for the provided project! It seems that the issue is reproducible when trying to render the RadChart inside a modal page. Confirming this as a bug - please keep track on this issue for possible solutions and fix.

Steps to reproduce the issue:
- use[ this test project](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-ui-feedback/chartTest)
- the initial page and the modal page are using the same RadChart snippets and sources.
- tap on `Open Modal` and the Chart is loaded without the Legend view.
- the RadChart on the initial page is working as expected.

**Comment by lini** [comment]
not able to reproduce this with the current (3.7.0) version of nativescript-ui-chart as well as the last released nativescript-pro-ui version.
