### ISSUE TITLE
ListView: Flicker with manual load on demand

### ISSUE THREAD

**Issue by tgpetrov** [telerik/nativescript-ui-feedback#462]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
_Yes_

### Tell us about the problem
_When loading items with variable item size on demand the whole list flickers_

### Which platform(s) does your issue occur on?
_iOS_

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application [sdk](https://github.com/telerik/nativescript-ui-samples/tree/master/sdk).
2. Go to ListView->Load on Demand->Manual with Variable Item Size
3. Scroll to the bottom and tap to add more items
4. You will see the following flicker:
![manual_load](https://user-images.githubusercontent.com/6085251/33944886-1bc113f2-e026-11e7-98c5-a4abaae1e95c.gif)

**Comment by BasyaLipman** [comment]
@tgpetrov I have this issue now, with ns 4.1 and ng 6. Flickering and moving to the beginning of the list when Load More is clicked on iOS only. (Works fine on Android). 

I have verified that pullToRefresh is not being called when I click Load More, so that is not the cause of the issue. It seemed from reading the various GitHub issues that this should no longer be an issue. Any idea what might be causing it?

**Comment by BasyaLipman** [comment]
My problem was caused by wrapping the ng-templates in *ngIf directive. Switching to the approach described [here](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/sdkAngular/app/listview/multiple-templates/listview-multiple-templates.component.ts) worked.

**Comment by NeriCodec** [comment]
I use RadListView and me solutions is in version "nativescript-ui-listview": "^3.5.11"
