### ISSUE TITLE
Regex on Android Broken

### ISSUE THREAD

**Issue by glen-stephens** [telerik/nativescript-ui-feedback#464]
For RadDataForm:
Doing basic credit card validation and \d{16} returns true after 11 numbers.  \d{1} through \d{11} works, but anything beyond 11 does not work. 

<df:RegExValidator regEx="\d{16}" errorMessage="Please enter a credit card number without spaces or hyphens"/> this passes validation as soon as 11 numbers have been entered on Android but works correctly on iOS.

Just figured out that this is broken only when the editor type is "Number".  Appears it is evaluating as a 32 bit integer.  I changed my editor type to Phone and it works.

**Comment by VeeK727** [comment]
This issue still exists. Why was it closed?

**Comment by tgpetrov** [comment]
Hi @VeeK727, the reason the issue is closed is that as the OP suggested the number editor just doesn't support unlimited range of numbers. It is limited by java's Integer.MAX_VALUE ([more info](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#MAX_VALUE)). In order to allow typing longer values, you need to use editor type `Phone` or `Text` and the property that the editor is editing should be of type `string`.

**Comment by VeeK727** [comment]
Oh okay. Got it
