### ISSUE TITLE
Is there a DateTimePicker?

### ISSUE THREAD

**Issue by LorenDorez** [telerik/nativescript-ui-feedback#466]
I see there is a DatePicker and a Time Picker but i need a DateTimePicker combined. does the pro-ui have this or any plans to implement

**Comment by tsonevn** [comment]
Hi @LorenDorez,
First of all, thank you for your interest in UI for NativeScript.
Indeed DataForm component does not have an editor, which combines DatePicker and TimePicker.
Regarding that, you could use the available ones and to set up their position to be in one row while using GridLayout. For example:
```
<df:PropertyGroup collapsible="true" name="test" hidden="false" >
                <df:PropertyGroup.layout>		
                  <df:DataFormGridLayout />		
                </df:PropertyGroup.layout>
                <df:PropertyGroup.properties>
                    <df:EntityProperty name="datefield" index="0" columnIndex="0">
                        <df:EntityProperty.editor>
                            <df:PropertyEditor type="DatePicker" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
                    <df:EntityProperty name="timefield" index="0" columnIndex="1">
                        <df:EntityProperty.editor>
                            <df:PropertyEditor type="TimePicker" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
                </df:PropertyGroup.properties>
            </df:PropertyGroup>
```
If this is not applicable to you, please provide some more info about your use-case and info why you will need similar editor's type instead of using individually DatePicker and TimePicker.
