### ISSUE TITLE
RadSideDrawer issues inconsistent warning message with webpack & uglify

### ISSUE THREAD

**Issue by manoldonev** [telerik/nativescript-ui-feedback#477]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
Yes

### Tell us about the problem
RadSideDrawer issues inconsistent and/or incorrect warning message when bundling the JS Tab template (https://github.com/NativeScript/template-tab-navigation) with webpack and uglify.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.3.0
- **CLI:** 3.4.0
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.0

### Please tell us how to recreate the issue in as much detail as possible.
1. `tns create drawer-webpack --template https://github.com/NativeScript/template-drawer-navigation`
2. `tns run android --bundle --env.uglify` outputs `JS: Warning: 'n' is not supported when 'showOverNavigation' is set to 'true'.` when running the app. We found out it is somehow related to setting the SlideInOnTopTransition for all drawer transitions in the template as when transition setter is commented out, there is no warning.
3. `tns run android --bundle` -- issues no warning as well.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_

**Comment by VladimirAmiorkov** [comment]
Hi @manoldonev ,

Thank you for reporting this. I researched the cause of this issue and it is caused by the fact that the "showOverNavigation" which is set to "true". Setting this with he default `drawerTransition` is ok and will function as expected but that functionality is not supported with some of the values of the `drawerTransition`. In the cases where it is not supported we are fallbacking to the default value of the `drawerTransition` and raising an warning message. Now when the uglify has been trigged it is changing the JS as expected but it also "breaks" the implementation of the check if  the current `showOverNavigation` + `drawerTransition` is supported leading to the mentioned inconsistent warning message.

Currently we are in the process of reworking the `showOverNavigation` and the RadSideDrawer overall for the upcoming NativeSript 4.0 and this condition will no longer be required so it will not be an issue. For now in the current 3.4 version you can simply ignore this warning message if you are not changing the `drawerTransition` and the drawer will work as expected. Note to be careful if you are using uglify with `showOverNavigation="true"` and the `drawerTransition` set to `RevealTransitionString`, `ReverseSlideOutTransitionString`, `ScaleDownPusherTransitionString`, `ScaleUpTransitionString`, or `SlideAlongTransitionString` in this case it is possible that the RadSideDrawer maybe work unexpected.

**Comment by VladimirAmiorkov** [comment]
This is resolved in the latest "next" version (0.10.0-2018-01-29-01) of the nativescript-dev-webpack plugin by this PR https://github.com/NativeScript/nativescript-dev-webpack/pull/426

Closing this issue. After the nativescript-dev-webpack is published or when NativeScript 4.0 is release as I mentioned above comment this issue will be fixed.

**Comment by manoldonev** [comment]
@VladimirAmiorkov Thanks!
