### ISSUE TITLE
iOS RadListView: weird itemLoading behaviour since latest nativescript-pro-ui@3.3.0

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#496]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
_Yes_

### Tell us about the problem
Usually, the itemLoading event is raised only for the list-items that are currently visible in the page and when you scroll up and down in the RadListView. Since latest nativescript-pro-ui update, I notice a weird behaviour on iOS. All list items are loaded at once, not only the ones that need to be rendered. That makes the loading process very slow. Everything works as expected on Android, like in the previous versions of the plugin.

This is a sample ListView with 200 items using
[nativescript-pro-ui@3.2.0](https://media.giphy.com/media/l49JTZl2JmNCVnlug/giphy.gif)
[nativescript-pro-ui@3.3.0](https://media.giphy.com/media/l49JXGxU2vOrZfpzG/giphy.gif)

### Which platform(s) does your issue occur on?
_iOS_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.3.0
- **CLI:** 3.4.1
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_Sample app can be found [here](https://drive.google.com/open?id=1kZWZaQs6tOTIFkqSjxHcmx0GfUel5B8o)_

**Comment by tsonevn** [comment]
Hi @felix-idf,
Thank you for reporting this issue. 
I tested this case on my side while using the attached sample and I was able to recreate the same behavior while using nativescirpt-pro-ui version 3.3.0.
For further info about the problem, please keep track on the issue.

**Comment by felix-idf** [comment]
This issue seems not to be related to nativescript-pro-ui only. I just migrated to tns-core-modules@3.4.0 and runtimes@3.4.1 and notice the same issue on iOS when using the older nativescript-pro-ui@3.2.0 version.

**Comment by VladimirAmiorkov** [comment]
Related to https://github.com/telerik/nativescript-ui-feedback/issues/641

**Comment by VladimirAmiorkov** [comment]
Hi @felix-idf ,

After investigating this issue and when it was introduced as you mentioned I am here to update you on the current state. Since the 3.3.0 version of nativescript-pro-ui a lot of things has changed, the plugin has been split into separate plugins for each component (nativescript-ui-listview, nativescript-ui-calendar etc.), also there has been multiple releases with new features and fixes. Looking at the version 3.3.0 of the now deprecated package, this was around the time when support for the ObservableArray actions (add, remove) was added to the RadListView component. Having said that looking at the source code of the provided sample project I see that you populating the items property of the RadListView by binding it to an empty ObservableArray after which you are adding new items one by one. While this may seam like a legit way of populating the bound collection what happens is that the RadListView is doing a lot of work because those ObservableArray actions are actually triggering a lot of its build in functionality like (measuring all of the elements so that functionality like "Load on demand" and "Pull to refresh" can execute they animations smoothly).

On a side note we have found another issue where the itemsLoading event is triggered multiple times and it is logged [here](https://github.com/telerik/nativescript-ui-feedback/issues/523). We are already working on a fix for this and it should be available in the next [nativescript-ui-listview](https://market.nativescript.org/plugins/nativescript-ui-listview) version by the end of the week. 

So after all this said the shown in the sample project approach of populating the bound items one by one is not recommended due to it being way too "heavy" for an initial setup, it would be way better to simply pass the entire array of items to the ObservableArray rather than calling its `push()` method one by one. Simply create a "temp" collection and after you "initialize" your items set it to the bound property:
```
var observableModule = require("data/observable");
var observableArrayModule = require("data/observable-array");

exports.vmMain = observableModule.fromObject({
    items: new observableArrayModule.ObservableArray(),
    tempItems: new observableArrayModule.ObservableArray(),


    init: function () {
        var self = this;

        for(var i = 0; i < 200; i++) {
            self.get('tempItems').push({
                title: "Title " + i,
                description: "This is the description of data item " + i
            });
        }
        this.items = this.tempItems;
    }
});
```

I will close this issue, if you have any followups please let me know.

**Comment by felix-idf** [comment]
Hi @VladimirAmiorkov ,

thanks for your explanation. I understand the problem of pushing every single item one by one into the observable-array. So that's why I tried to do it this way:

```
exports.vmMain = observableModule.fromObject({
    items: new observableArrayModule.ObservableArray(),

    loadData: function() {
        var self = this;

        return new Promise(function (resolve, reject) {
            http.getJSON("https://restcountries.eu/rest/v2/all").then(function(response) {
                console.log("clear datasource...");

                self.get('items').splice(0, self.get('items').length);

                console.log("datasource is empty, now push new items-array...");

                self.get('items').push(response);

                console.log("pushed items... now resolve...");

                resolve();
            }, function (e) {
                console.log(e);
                reject();
            });
        });
    }
});
```

So I push the whole array from the json response one single time into the datasource:
`self.get('items').push(response);`

But as a result, the list still takes a lot of time to render on iOS as you can see here:
![itemloading_issue](https://user-images.githubusercontent.com/6443021/43786116-3068ce24-9a68-11e8-90b6-d68adbde8e64.gif)

You can see an updated version of this sample app with the latest dependencies of the tns-core-modules, tns-ios and nativescript-ui-listview here:
[RLVIOSItemLoadingIssue.zip](https://github.com/telerik/nativescript-ui-feedback/files/2267045/RLVIOSItemLoadingIssue.zip)

You only need to start the app and watch for the logs in the console.
When the list is loaded, you can use pull-to-refresh to see the behaviour again.



I also tried to use a temp datasource, like you suggested it in your last post in this thread:

```
exports.vmMain = observableModule.fromObject({
    items: new observableArrayModule.ObservableArray(),
    itemsTemp: new observableArrayModule.ObservableArray(),

    loadData: function() {
        var self = this;

        return new Promise(function (resolve, reject) {
            http.getJSON("https://restcountries.eu/rest/v2/all").then(function(response) {
                self.get('itemsTemp').splice(0, self.get('items').length);
                self.get('itemsTemp').push(response);

                self.set("items", self.get('itemsTemp'));
                resolve();
            }, function (e) {
                console.log(e);
                reject();
            });
        });
    }
});
```

This way, the list indeed is filled much faster. HOWEVER, the problem is using the pull to refresh functionality.... there the list still needs a lot of time to update:

![itemloading_issue_2](https://user-images.githubusercontent.com/6443021/43787387-292c10dc-9a6b-11e8-9657-c3b626eade85.gif)


So it would be great if you could reinvestigate this issue and maybe you can tell me what to do, if this issue is caused by a wrong usage of the observable-array's funcionality.

Thank you in advance

**Comment by Burgov** [comment]
@VladimirAmiorkov in our case we're using the RLV to render a calendar with a restricted range, going into max 2 years. We already have the complete data set and there's no server interaction either. But since on iOS it's trying to render the full range of 2 years, instead of max 6 weeks at a time, we had to implement a workaround.

**Comment by VladimirAmiorkov** [comment]
@Burgov ,

Hi just to clarify are you also populating the items of the `RadListView` inside the `pullToRefreshInitiated` event ? In the latest version of the _nativescript-ui-listview_ navigating to a `Page` that contains a `RadListView` with initially set big source as `items` should not encounter any slowdowns. In the above case the issue is that a big collection is set to the `items` inside the pull to refresh callback which requires the entire list to render all of its items.
