### ISSUE TITLE
Bug: [iOS] Application crash if you set horizontalZoom on Chart via XML and the bound data is undefined

### ISSUE THREAD

**Issue by PeterStaev** [telerik/nativescript-ui-feedback#5]
I have a chart whose data is not loaded yet and the chart is hidden. If i don't set `horizontalZoom` on the chart it works as expected. But if I set `horizontalZoom` via XML the chart cause the application to crash with exception `capacity (214783646) is ridiculous`. I tried pre-initing the bound array of data with an empty one, but then it crashes with `cannot access object at index 0 for empty array`

**Comment by NickIliev** [comment]
The issue is not reproducible with the latest nativescript-pro-ui version.
Here are the steps taken when trying to reproduce the issue:

- using [this example](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/chart/series/area/area-series.xml)
- introduced `horizontalZoom` in the XML
```
<chart:RadCartesianChart id="cartesianChart" horizontalZoom="3">
```
- introduced setTimeOut to delay the intialization of the items source
```
export function onPageLoaded(args){
    var page = args.object;
    setTimeout(() => {
        page.bindingContext = new dataModelModule.CategoricalDataModel();
    }, 3000);
}
```

Result - the chart data is visualized after 3 seconds with applied horizontal zoom.

@PeterStaev do let me know if you are still experiencing this issue.
