### ISSUE TITLE
RadListView - LoadOnDemand - Android  - "Load More" template not working

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#55]
Issue reproducible with Angular app on Android

[LoadOnDemand](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/load-on-demand) has the option to provide custom template for the "Load More" functionality with **_*tkListLoadOnDemandTemplate_** 

```
<GridLayout *tkListLoadOnDemandTemplate class="loadOnDemandItemGridLayout">
      <Label text="Load More" horizontalAlignment="center" verticalAlignment="center"></Label>
</GridLayout>
```

On Android, the template will render, but the **loadMoreDataRequested** will not trigger and new items won't load at all. (working as expected in iOS)

Steps to reproduce:

- start [this example](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/listview/load-on-demand) for Android
- add the template with **_*tkListLoadOnDemandTemplate_**
- try to load more items

related to **t 1088631**

**Comment by anuragd7** [comment]
By when can we expect a solution to this? Thanks

**Comment by VladimirAmiorkov** [comment]
@anuragd7 We are doing our best in resolving all of the issues we receive from the community. This one is especially import which is why I have increased its priority.

We will do our best to resolve this for our next official release.

**Comment by anuragd7** [comment]
Thank you

**Comment by Natalia-Hristova** [comment]
This issue is fixed and it will be available in our next official release. If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` . 
**NOTE** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.
