### ISSUE TITLE
Spinner on the RadListView loadOnDemand=auto does not hide by itself unless i tap on it or do a pull to refresh

### ISSUE THREAD

**Issue by ngunhaSO** [telerik/nativescript-ui-feedback#581]
I notice that the spinner on the RadListview does not disappear when set loadOnDemand=auto until I either tap on the spinner or do a pull to refresh. Is this the expected behavior?

My tns version is: 3.4.3
And I download directly the sample app from: https://github.com/telerik/nativescript-ui-samples-angular

**Comment by ngunhaSO** [comment]
Let say from the beginning, I only have 2 items, so there will be a huge amount of blank space along with a spinner which will be awkward for UI

**Comment by prabudevarrajan** [comment]
I am also facing same issue. Any workaround?

**Comment by tgpetrov** [comment]
If I understand correctly the issue is that when initially there is a small number of items (say 2) and the loading indicator is visible, it doesn’t go away. The first observation in this scenario is that the indicator is visible from the beginning which is the expected behavior, because when you see the end of the list, you obviously need to load more items. The second observation is that even if it seems that the list is loading, it isn’t, the loading event is not fired, the items are not loaded and the indicator never disappears. This is due to the fact that the actual check for whether the list needs loading, currently is performed only when the list is scrolled. This is a bug that we will address for a future release.

**Comment by marablec** [comment]
has this been fixed?

**Comment by tgpetrov** [comment]
Hi @marablec,
Yes, it was fixed and released with nativescript-ui-listview@3.5.3.
Here are the [release notes](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/listview.md#v353).

**Comment by darkmantle** [comment]
This hasn't been fixed.. I have a list with currently just one item in it (there will be more at some points, its dynamic), and the loading icon does not disappear at all. I

I'm on version 3.8.0

**Comment by marablec** [comment]
I am using 3.6.1 and it is broken.

**Comment by fhackenb** [comment]
@tgpetrov also seeing this issue in 5.2.0. Like @marablec asked is there a way to just not have the spinner show at all?

**Comment by tgpetrov** [comment]
The issue that was logged initially can be demonstrated with [this playground](https://play.nativescript.org/?template=play-tsc&id=j5OFTy).

The behaviour is: very few items loaded initially; as they don't fill the screen, loading indicator is shown immediately; new items are loaded until the screen is filled. This was not working prior to nativescript-ui-listview@3.5.3 and was fixed in that version.

If the desired behaviour is to not have the indicator initially, _loadOnDemandMode_ can also be [None](https://docs.nativescript.org/ns-ui-api-reference/enums/listviewloadondemandmode#none), but then there is no loading on demand. 

If someone has encountered something similar please open a new issue with a Playground (or precise reproduction steps) that demonstrates how you reproduce the described issue.
