### ISSUE TITLE
RadSideDrawer clicking on Edge opens automatically

### ISSUE THREAD

**Issue by bhavincb** [telerik/nativescript-ui-feedback#648]
i had position SideDrawer to the left side.
not clicking element near the left edge doesn'y trigger tap event function instead try to opn sideDrawer.
here is the playground demo for this bug.

[https://play.nativescript.org/?template=play-ng&id=2pRk6A](https://play.nativescript.org/?template=play-ng&id=2pRk6A)

in above demo tapping red color Label with text `CL` . slightly opens side drawer.

**Comment by NickIliev** [comment]
@bhavincb  regarding the issue the behavior is expected as you have a really small actionable space. In fact, the tap is working when you assign a callback function (which was missing from the code-behind file) - revised Playground demo showing what I mean can be found [here](https://play.nativescript.org/?template=play-ng&id=2pRk6A&v=2) - your original labels can be tapped only in the text content as they don't have any width their width is just as the text content (so this is the tappable area)

**Comment by bhavincb** [comment]
hii @NickIliev ,
the current behavior can not be considered as expected behavior. because even if i have small actionable space. tapping it should not open the side drawer. in fact, event if i assign a callback function tapping near 5 to 10 pixel to the edge doesn't trigger tap event. also side drawer is expected to open on swipe gesture it shouldn't be open on tapping it. i had checked in many popular android apps. none of them have this issue.

**Comment by edusperoni** [comment]
Honestly, this is somewhat annoying. Most of other apps side drawers have a small delay before triggering the drag gesture, so you don't accidentally trigger the drawer on a single tap, but this delay seems non-existent in nativescript.

I believe this may actually be a bug with the way nativescript handles gestures, because I sometimes miss a tap and it seems it's because the swipe gesture detection is just too sensitive, but further testing is required on this specific point.

But the drawer showing on a tap should definitely not be expected behavior.
