### ISSUE TITLE
nativescript-ui-chart - RadCartesianChart valueProperty doesn't display when datasource changes from code

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#796]
_From @janossuta on August 16, 2018 19:39_

Hi,

I have a problem with `RadCartesianChart` when I updating the datasource from code the `valueProperty` doesn't display at all only the `categoryProperty` shows. 

I'm using Andorid 8.0.0 for testing

I've set up a playgroud to reproduce the issue:
https://play.nativescript.org/?template=play-ng&id=P8WPCT

my code is in the `home.component.ts` file

Could somebody help me with this issue? Am I doing something wrong?

_Copied from original issue: NativeScript/NativeScript#6192_

**Comment by tsonevn** [comment]
HI @janossuta,
You have set up `valueProperty` to `Amount`, which is no declared as a property in your array's ViewModel. You should change `valueProperty="Amount"` with `valueProperty="Content"` and the content of the Chart should be displayed. For your convenience, I am attaching a [link](https://play.nativescript.org/?template=play-ng&id=P8WPCT&v=2) to your Playground project, with the needed change.

**Comment by janossuta** [comment]
Hi @tsonevn,

Thank you for your answer!
Well then that was just a typo from my side :S at least there is nothing wrong with the plugin :)
Unfortunately the problem is still remain in my app. 
I got the data from firebase and when I push a new item in the array I got a similar issue as with the typo but if I add a value manually to the array everything is fine. I run the event though zonedCallback but still not working.

 Have you encountered something like this?
