### ISSUE TITLE
Cannot set text field on RadAutoCompleteTextView

### ISSUE THREAD

**Issue by neil-119** [telerik/nativescript-ui-feedback#808]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes, I created an example playground below.

### Tell us about the problem
I'm trying to pre-populate some text into the autocomplete view when the page loads (see this simplified [example playground](https://play.nativescript.org/?template=play-ng&id=oFje0u&v=2)). In ngOnInit, I'm doing:

     this.autocomplete.autoCompleteTextView.text = "Test!";

But that has no effect. However, according to the [documentation](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/AutoCompleteTextView/getting-started), the `The text property allows you to change the autocomplete text or get the current user input.` It's not working on the latest nativescript-ui-autocomplete v3.9.0.

### Which platform(s) does your issue occur on?
Android / iOS

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** `"nativescript-ui-autocomplete": "^3.9.0"`
- **CLI:** 4.2.0
- **Cross-platform modules:** 4.2.0
- **Runtime(s):**
	"tns-ios": {
	  "version": "4.1.1"
	},
	"tns-android": {
	  "version": "4.2.0"
	}

### Please tell us how to recreate the issue in as much detail as possible.
In the [playground example](https://play.nativescript.org/?template=play-ng&id=oFje0u&v=2), you would expect the autocomplete to function as described in the documentation, but it does not.

**Comment by elena-p** [comment]
Hi @neil-119,

I apologise for the late response. I reviewed your playground example an it works as expected on iOS, but doesn't set the text into the autocomplete view in android. 

The issue in android is caused because the `ngOnInit` event is fired before the native view is created. You can check more about angular events [here](https://github.com/NativeScript/nativescript-angular/issues/1192#issuecomment-363676815). 

In your case, you need to attach to the loaded event of the AutoCompleteTextView. You can check the updated playground example [here](https://play.nativescript.org/?template=play-ng&id=oFje0u&v=3).
