### ISSUE TITLE
Unable to Add Custom Template for Group Title in RadListView for Vue.js

### ISSUE THREAD

**Issue by suxur** [telerik/nativescript-ui-feedback#972]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
Unable to define a custom template for GroupView in RadListView using Vue

### Which platform(s) does your issue occur on?
iOS, not developing for Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 5.0.1
- **CLI:** 5.1.0
- **Cross-platform modules:** 5.1.0
- **Runtime(s):** 5.1.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-vue&id=hO4KIr&v=2

**Comment by tsonevn** [comment]
Hi @suxur,
Thank you for the provided sample project. I was able to recreate the issue on my side. I will mark this as a bug. You can keep track of the issue for further info.

**Comment by zbranzov** [comment]
@msaelices 
There is an error using the group template on android. It happens when I open the demo example:

System.err: com.tns.NativeScriptException:
System.err: Calling js method onBindGroupViewHolder failed
System.err:
System.err: TypeError: Cannot read property 'name' of undefined
System.err: File: "<unknown>, line: 3, column: 763
System.err:
System.err: StackTrace:
System.err:     Frame: function:'fn', file:'', line: 3, column: 764
System.err:     Frame: function:'patchTemplate', file:'file:///data/data/org.nativescript.demovueradlistview/files/app/vendor.js', line: 11288, column: 43
System.err:     Frame: function:'updateViewTemplate', file:'file:///data/data/org.nativescript.demovueradlistview/files/app/vendor.js', line: 4360, column: 35
System.err:     Frame: function:'onItemLoading', file:'file:///data/data/org.nativescript.demovueradlistview/files/app/vendor.js', line: 4363, column: 12
System.err:     Frame: function:'invoker', file:'file:///data/data/org.nativescript.demovueradlistview/files/app/vendor.js', line: 8515, column: 18
System.err:     Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.demovueradlistview/files/app/vendor.js', line: 22045, column: 15
System.err:     Frame: function:'ListViewDataSourceAdapter.onBindGroupViewHolder', file:'file:///data/data/org.nativescript.demovueradlistview/files/app/vendor.js', line: 1859, column: 15

On iOS the group template works but the item names don't correspond. https://screencast.com/t/KQjoASiSY9H

**Comment by msaelices** [comment]
@zbranzov Ok, I will take a look.

**Comment by zbranzov** [comment]
The feature is released in the nativescript-ui-listview@5.2 version. 
Sample usage:
```
<RadListView for="item in itemList" :groupingFunction="getItemGroup">
        <v-template name="group">
          <Label :text="item.category + ' items'" class="green"/>
        </v-template>
        <v-template>
          <StackLayout class="item" orientation="vertical">
            <Label :text="item.name" class="nameLabel"></Label>
          </StackLayout>
        </v-template>
      </RadListView>
```

**Comment by devlinpadayachee** [comment]
Does anyone have a full example of this implementation, I cant get it to work.

`<RadListView ref="listView" for="task in tasksLite" @itemTap="goToDetailPage(task)" pullToRefresh="true" @pullToRefreshInitiated="onPullToRefreshInitiated" :groupingFunction="getTaskGroup">
            <v-template name="group">
               <Label :text="task.priority + ' items'" class="green"/>
            </v-template>
            <v-template>
              <StackLayout class="item" orientation="vertical">
                <Label :text="task.name" class="nameLabel"></Label>
              </StackLayout>
            </v-template>
          </RadListView>`

`getTaskGroup(task) {
      return task.priority;
    },`

**Comment by MrDenzzz** [comment]
> <Label :text="task.name" class="nameLabel"></Label>

`:text="task.category"`

**Comment by MrDenzzz** [comment]
@devlinpadayachee try `:text="task.category"`
